### ISSUE TITLE
Ada File/Folder di Luar Pertemuan

### ISSUE THREAD

**Issue by hadihammurabi** [hamdanir/naya-kursus#2]
Mas @hamdanir file/folder berikut berada di luar folder pertemuan.
<img width="333" alt="image" src="https://user-images.githubusercontent.com/16364286/216800495-8603a696-a134-4e1f-8d69-ede63cc8dcba.png">

Jika ada kaitannya dengan pertemuan tertentu, silakan dimasukkan ke dalamnya ya.
Supaya repo-nya lebih rapi lagi

**Comment by hamdanir** [comment]
Siap mas
